### ISSUE TITLE
Not giving the option to save password to team

### ISSUE THREAD

**Issue by juancobe** [WeAreWizards/passopolis-server#10] opened 2015-11-24 04:01 UTC
I'm the creator of a team in Passopolis. When using a new password on a site, the passopolis dialog does not give me the option to save the newly used password on my team's account. Just on my personal account. 
<img width="796" alt="screen shot 2015-11-23 at 11 00 32 pm" src="https://cloud.githubusercontent.com/assets/3697998/11357535/201bccb6-9236-11e5-8d5a-c01c1c5324cc.png">

**Comment by amenk** [comment] 2016-09-13 11:44
Wrong repo and duplicate of https://github.com/WeAreWizards/passopolis-extensions/issues/31

please close :-)

**Closed as completed** 2016-09-13 13:41 UTC
